variables:
    - name: SYMFONY_ENV
      value: prod
    - name: XDEBUG_REMOTE_ENABLED
      value: 0
    - name: XDEBUG_REMOTE_HOST
      value: sshforward
    - name: XDEBUG_REMOTE_PORT
      value: 9000

tasks:
    images:
        build:
            services:
                web:
                    image: ${IMAGE_NAME}
                    naming_strategy: sha1
    deployment:
        deploy:
            cluster: ${CLUSTER}
            environment:
                name: '"sfdemo-" ~ code_reference.branch'
            services:
                sshforward:
                    condition: 'code_reference.branch matches "/^cpdev/"'
                    specification:
                        ports:
                            - 9000
                        environment_variables:
                            SSH_FORWARD_PASSWORD: ${SSH_FORWARD_PASSWORD}
                web:
                    specification:
                        accessibility:
                            from_external: true
                        environment_variables:
                            - name: SYMFONY_ENV
                              value: ${SYMFONY_ENV}
                            - name: XDEBUG_REMOTE_ENABLED
                              value: ${XDEBUG_REMOTE_ENABLED}

pipelines:
  - name: Production
    condition: 'code_reference.branch in ["master"]'
    tasks: [ images, deployment ]
  - name: Feature
    condition: 'code_reference.branch matches "/^feature/"'
    tasks: [ images, deployment ]
  - name: Remote
    condition: 'code_reference.branch matches "/^cpdev/"'
    tasks: [ images, deployment ]
    variables:
      - name: SYMFONY_ENV
        value: prod
      - name: XDEBUG_REMOTE_ENABLED
        value: 1