version: "2"
services:
    sshforward:
        image: quay.io/continuouspipe/ssh-forward:latest
    web:
        build: .
        expose:
            - 80
            - 443
        ports:
            - "8080:80"
            - "443:443"
        volumes:
            - .:/app
        depends_on:
            - sshforward
