version: "2"
services:
    web:
        build: .
        expose:
            - 80
            - 443
        ports:
            - "8080:80"
            - "443:443"
        volumes:
            - .:/app
